const dotenv = require('dotenv');

dotenv.config();

module.exports = {
    PORT: process.env.PORT,
    SERVICE_NAME: process.env.SERVICE_NAME,
    SERVICE_ENCRYPTION_KEY: process.env.SERVICE_ENCRYPTION_KEY,
    SERVICE_TOKEN_EXPIRY_IN_SECONDS: process.env.SERVICE_TOKEN_EXPIRY_IN_SECONDS,
    SALT_ROUNDS: process.env.SALT_ROUNDS,
    JWT_SECRET: process.env.JWT_SECRET,
    JWT_EXPIRY: process.env.JWT_EXPIRY,
    SYSTEM_ADMIN_EMAIL: process.env.SYSTEM_ADMIN_EMAIL,
    SYSTEM_ADMIN_PASSWORD: process.env.SYSTEM_ADMIN_PASSWORD,
    BOOKING_SERVICE: process.env.BOOKING_SERVICE,
    FLIGHT_CREATION_SERVICE: process.env.FLIGHT_CREATION_SERVICE,
    FLIGHT_SEARCHING_SERVICE: process.env.FLIGHT_SEARCHING_SERVICE,
    FLIGHT_BOOKING_SERVICE: process.env.FLIGHT_BOOKING_SERVICE,

    RABBITMQ_HOST: process.env.RABBITMQ_HOST,
    RABBITMQ_USERNAME: process.env.RABBITMQ_USERNAME,
    RABBITMQ_PASSWORD: process.env.RABBITMQ_PASSWORD,
    AIRLINE_ADMIN_REQ_QUEUE: process.env.AIRLINE_ADMIN_REQ_QUEUE,
    AIRLINE_ADMIN_RES_QUEUE: process.env.AIRLINE_ADMIN_RES_QUEUE,
}